# =============================================================
# Deployment Manifest
# =============================================================
# This file represents a production deployment configuration.
#
# CANDIDATE TASK: Your CD pipeline should update this file
# with the new image tag on successful deployments to main.
#
# The image_tag field should be updated to the commit SHA
# when a deployment occurs.
# =============================================================

apiVersion: v1
kind: deployment
metadata:
  name: agent-api
  environment: production

spec:
  replicas: 2

  container:
    name: agent-api
    # TODO: This should be updated by the CD pipeline
    image_tag: "2eb839644493872445fc2ebce8bff9067bd8fa75"
    port: 8080

    env:
      - name: PROMPT_VERSION
        value: "v1.0.0"

    resources:
      cpu: "500m"
      memory: "512Mi"

    healthcheck:
      path: /healthz
      interval: 10s
      timeout: 5s

# Deployment History (updated by CI/CD):
# -------------------------------------------------------------
# | Timestamp | Commit SHA | Deployed By |
# -------------------------------------------------------------
# | (will be populated by CD pipeline)  |
# -------------------------------------------------------------
# | 2026-02-15T16:19:33Z | 3d80be3b9e5e08edcee48a127d1da27b0d7d1bf1 | tinnapopd |
# | 2026-02-15T16:28:08Z | f554bd56c52d3b211a5aaa13475b1522565934f7 | tinnapopd |
# | 2026-02-16T02:13:20Z | ad176dc3c1d8a919d2745fc89bec7616e555912f | tinnapopd |
# | 2026-02-16T13:58:47Z | 2eb839644493872445fc2ebce8bff9067bd8fa75 | tinnapopd |
